spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/mysql/migration