spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/appdb
    username: pguser
    password: pgpass
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/postgres/migration
